#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const long long MOD = 998244353;

void solve(long long K, long long N, std::vector<long long> x){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long K;
    std::scanf("%lld", &K);
    long long N;
    std::scanf("%lld", &N);
    std::vector<long long> x(K);
    for(int i = 0 ; i < K ; i++){
        std::scanf("%lld", &x[i]);
    }
    solve(K, N, std::move(x));
    return 0;
}
