#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, std::vector<long long> w, std::vector<long long> s, std::vector<long long> v){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    std::vector<long long> w(N);
    std::vector<long long> s(N);
    std::vector<long long> v(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &w[i]);
        std::scanf("%lld", &s[i]);
        std::scanf("%lld", &v[i]);
    }
    solve(N, std::move(w), std::move(s), std::move(v));
    return 0;
}
