#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long W, long long H, std::vector<long long> p, std::vector<long long> q){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long W;
    std::scanf("%lld", &W);
    long long H;
    std::scanf("%lld", &H);
    std::vector<long long> p(W);
    for(int i = 0 ; i < W ; i++){
        std::scanf("%lld", &p[i]);
    }
    std::vector<long long> q(H);
    for(int i = 0 ; i < H ; i++){
        std::scanf("%lld", &q[i]);
    }
    solve(W, H, std::move(p), std::move(q));
    return 0;
}
