#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const long long MOD = 998244353;

void solve(long long N, long long K, std::vector<long long> C, std::vector<std::vector<long long>> A){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    long long K;
    std::scanf("%lld", &K);
    std::vector<long long> C(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &C[i]);
    }
    std::vector<std::vector<long long>> A(N, std::vector<long long>(6));
    for(int i = 0 ; i < N ; i++){
        for(int j = 0 ; j < 6 ; j++){
            std::scanf("%lld", &A[i][j]);
        }
    }
    solve(N, K, std::move(C), std::move(A));
    return 0;
}
