#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, long long T, long long L, std::vector<long long> u, std::vector<long long> v){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    long long T;
    std::scanf("%lld", &T);
    long long L;
    std::scanf("%lld", &L);
    std::vector<long long> u(T);
    std::vector<long long> v(T);
    for(int i = 0 ; i < T ; i++){
        std::scanf("%lld", &u[i]);
        std::scanf("%lld", &v[i]);
    }
    solve(N, T, L, std::move(u), std::move(v));
    return 0;
}
