#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, long long K, long long L, std::vector<long long> p, std::vector<long long> q, std::vector<long long> r, std::vector<long long> s){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    long long K;
    std::scanf("%lld", &K);
    long long L;
    std::scanf("%lld", &L);
    std::vector<long long> p(K);
    std::vector<long long> q(K);
    for(int i = 0 ; i < K ; i++){
        std::scanf("%lld", &p[i]);
        std::scanf("%lld", &q[i]);
    }
    std::vector<long long> r(L);
    std::vector<long long> s(L);
    for(int i = 0 ; i < L ; i++){
        std::scanf("%lld", &r[i]);
        std::scanf("%lld", &s[i]);
    }
    solve(N, K, L, std::move(p), std::move(q), std::move(r), std::move(s));
    return 0;
}
