#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, long long g_A, long long s_A, long long b_A, long long g_B, long long s_B, long long b_B){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    long long g_A;
    std::scanf("%lld", &g_A);
    long long s_A;
    std::scanf("%lld", &s_A);
    long long b_A;
    std::scanf("%lld", &b_A);
    long long g_B;
    std::scanf("%lld", &g_B);
    long long s_B;
    std::scanf("%lld", &s_B);
    long long b_B;
    std::scanf("%lld", &b_B);
    solve(N, g_A, s_A, b_A, g_B, s_B, b_B);
    return 0;
}
