#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const long long MOD = 1000000007;

void solve(long long n, std::vector<long long> a){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long n;
    std::scanf("%lld", &n);
    std::vector<long long> a(n+1);
    for(int i = 0 ; i < n+1 ; i++){
        std::scanf("%lld", &a[i]);
    }
    solve(n, std::move(a));
    return 0;
}
