#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const long long MOD = 998244353;

void solve(long long R, long long G, long long B, long long K, long long X, long long Y, long long Z){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long R;
    std::scanf("%lld", &R);
    long long G;
    std::scanf("%lld", &G);
    long long B;
    std::scanf("%lld", &B);
    long long K;
    std::scanf("%lld", &K);
    long long X;
    std::scanf("%lld", &X);
    long long Y;
    std::scanf("%lld", &Y);
    long long Z;
    std::scanf("%lld", &Z);
    solve(R, G, B, K, X, Y, Z);
    return 0;
}
