#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const long long MOD = 13;
const string YES = "Yes";
const string NO = "No";

void solve(long long P, long long a, long long b){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long P;
    std::scanf("%lld", &P);
    long long a;
    std::scanf("%lld", &a);
    long long b;
    std::scanf("%lld", &b);
    solve(P, a, b);
    return 0;
}
