#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const string YES = "YES";
const string NO = "NO";

void solve(long long r, long long g, long long b){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long r;
    std::scanf("%lld", &r);
    long long g;
    std::scanf("%lld", &g);
    long long b;
    std::scanf("%lld", &b);
    solve(r, g, b);
    return 0;
}
