#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long sx, long long sy, long long tx, long long ty){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long sx;
    std::scanf("%lld", &sx);
    long long sy;
    std::scanf("%lld", &sy);
    long long tx;
    std::scanf("%lld", &tx);
    long long ty;
    std::scanf("%lld", &ty);
    solve(sx, sy, tx, ty);
    return 0;
}
