#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(long long R, long long C, long long N, std::vector<long long> r, std::vector<long long> c, std::vector<long long> a){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long R;
    std::scanf("%lld", &R);
    long long C;
    std::scanf("%lld", &C);
    long long N;
    std::scanf("%lld", &N);
    std::vector<long long> r(N);
    std::vector<long long> c(N);
    std::vector<long long> a(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &r[i]);
        std::scanf("%lld", &c[i]);
        std::scanf("%lld", &a[i]);
    }
    solve(R, C, N, std::move(r), std::move(c), std::move(a));
    return 0;
}
