#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long H, long long W, long long N, long long s_x, long long s_y, long long g_x, long long g_y, std::vector<long long> X, std::vector<long long> Y){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long H;
    std::scanf("%lld", &H);
    long long W;
    std::scanf("%lld", &W);
    long long N;
    std::scanf("%lld", &N);
    long long s_x;
    std::scanf("%lld", &s_x);
    long long s_y;
    std::scanf("%lld", &s_y);
    long long g_x;
    std::scanf("%lld", &g_x);
    long long g_y;
    std::scanf("%lld", &g_y);
    std::vector<long long> X(N);
    std::vector<long long> Y(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &X[i]);
        std::scanf("%lld", &Y[i]);
    }
    solve(H, W, N, s_x, s_y, g_x, g_y, std::move(X), std::move(Y));
    return 0;
}
