#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, long long M, long long K, long long L, std::vector<long long> A, std::vector<long long> B, std::vector<long long> U, std::vector<long long> V, std::vector<long long> C){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    long long M;
    std::scanf("%lld", &M);
    long long K;
    std::scanf("%lld", &K);
    long long L;
    std::scanf("%lld", &L);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &A[i]);
    }
    std::vector<long long> B(L);
    for(int i = 0 ; i < L ; i++){
        std::scanf("%lld", &B[i]);
    }
    std::vector<long long> U(M);
    std::vector<long long> V(M);
    std::vector<long long> C(M);
    for(int i = 0 ; i < M ; i++){
        std::scanf("%lld", &U[i]);
        std::scanf("%lld", &V[i]);
        std::scanf("%lld", &C[i]);
    }
    solve(N, M, K, L, std::move(A), std::move(B), std::move(U), std::move(V), std::move(C));
    return 0;
}
