#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, long long C, std::vector<std::vector<long long>> D, std::vector<std::vector<long long>> c){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    long long C;
    std::scanf("%lld", &C);
    std::vector<std::vector<long long>> D(C, std::vector<long long>(C));
    for(int i = 0 ; i < C ; i++){
        for(int j = 0 ; j < C ; j++){
            std::scanf("%lld", &D[i][j]);
        }
    }
    std::vector<std::vector<long long>> c(N, std::vector<long long>(N));
    for(int i = 0 ; i < N ; i++){
        for(int j = 0 ; j < N ; j++){
            std::scanf("%lld", &c[i][j]);
        }
    }
    solve(N, C, std::move(D), std::move(c));
    return 0;
}
