#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, long long W, long long C, std::vector<long long> l, std::vector<long long> r, std::vector<long long> p){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    long long W;
    std::scanf("%lld", &W);
    long long C;
    std::scanf("%lld", &C);
    std::vector<long long> l(N);
    std::vector<long long> r(N);
    std::vector<long long> p(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &l[i]);
        std::scanf("%lld", &r[i]);
        std::scanf("%lld", &p[i]);
    }
    solve(N, W, C, std::move(l), std::move(r), std::move(p));
    return 0;
}
