#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(long long N, long long T, std::vector<long long> AX, std::vector<long long> AY, std::vector<long long> BX, std::vector<long long> BY){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    long long T;
    std::scanf("%lld", &T);
    std::vector<long long> AX(N);
    std::vector<long long> AY(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &AX[i]);
        std::scanf("%lld", &AY[i]);
    }
    std::vector<long long> BX(N);
    std::vector<long long> BY(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &BX[i]);
        std::scanf("%lld", &BY[i]);
    }
    solve(N, T, std::move(AX), std::move(AY), std::move(BX), std::move(BY));
    return 0;
}
