#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long S_x, long long S_y, long long G_x, long long G_y){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long S_x;
    std::scanf("%lld", &S_x);
    long long S_y;
    std::scanf("%lld", &S_y);
    long long G_x;
    std::scanf("%lld", &G_x);
    long long G_y;
    std::scanf("%lld", &G_y);
    solve(S_x, S_y, G_x, G_y);
    return 0;
}
